model_types:
    -
        model_type_name: car
        dll_path: "D:/codeproject/simplecq/config/mymodel.dll"
        output_movable: false
    -
        model_type_name: agent
        dll_path: "D:/codeproject/simplecq/bin/RelWithDebInfo/agent.dll"
        output_movable: false

models:
    -
        model_type: car
        side_id: 1
        id: 1
        init_value: "<c><enableLog><bool>1</bool></enableLog><longitude><double>107.04836545797855</double></longitude><latitude><double>33.4384789646017</double></latitude><altitude><double>0</double></altitude><filePath><string>D:/cqmodel/rule_singlecarbattle/rule.xml</string></filePath><platoonid><uint64_t>1</uint64_t></platoonid><demFilePath><string>D:/codeproject/simplecq-master/config/zjc_wsb_demo1.tif</string></demFilePath><phyfilePath><string>D:/codeproject/simplecq/config/car.xml</string></phyfilePath></c>"
    -
        model_type: car
        side_id: 2
        id: 2
        init_value: "<c><enableLog><bool>1</bool></enableLog><longitude><double>107.12843674370725</double></longitude><latitude><double>33.455902551014006</double></latitude><altitude><double>0</double></altitude><filePath><string>D:/cqmodel/rule_singlecarbattle/rule_blue.xml</string></filePath><platoonid><uint64_t>2</uint64_t></platoonid><demFilePath><string>D:/codeproject/simplecq-master/config/zjc_wsb_demo1.tif</string></demFilePath><phyfilePath><string>D:/codeproject/simplecq/config/car.xml</string></phyfilePath></c>"
    -
        model_type: agent
        side_id: 1
        id: 3
        init_value: "<c><port><uint32_t>40029</uint32_t></port></c>"

   
topics:
    - 
        from: car
        members:
            - ForceSideID
            - State
            - longitude
            - latitude
        subscribers:
            - 
                to: root
                name_convert:
                    - {name: ForceSideID}
                    - {name: State}
                    - {name: longitude}
                    - {name: latitude}
    - 
        from: car
        members:
            - VID
            - FireDataOut
        subscribers:
            - 
                to: car
                name_convert:
                    -
                        src_name: VID
                        dst_name: FireID
                    - 
                        src_name: FireDataOut
                        dst_name: FireData
    - 
        from: car
        members:
            - EntityInfoOut
            - distance_out
        subscribers:
            - 
                to: car
                name_convert:
                    -
                        src_name: EntityInfoOut
                        dst_name: EntityInfo
            # - 
            #     to: agent
            #     name_convert:
            #         -
            #             src_name: EntityInfoOut
            #             dst_name: carInfo
                    # -
                    #     src_name: distance_out
                    #     dst_name: distance
    # - 
    #     from: agent
    #     members:
    #         - restart
    #     subscribers:
    #         - 
    #             to: car
    #             name_convert:
    #                 - {name: restart}
    # - 
    #     from: agent
    #     members:
    #         - targetDir
    #         - targetVel
    #     subscribers:
    #         - 
    #             to: car
    #             name_convert:
    #                 - 
    #                     src_name: targetDir
    #                     dst_name: pythonParam1
    #                 -
    #                     src_name: targetVel
    #                     dst_name: pythonParam2